### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by shiffman** [magicbookproject/magicbook#2]
What's the best way to approach custom fonts?  For example, I have a CSS file like so:

```CSS
 @font-face {font-family: 'ProximaNovaS-Thin';src: url('../fonts/23AC3F_3_0.eot');src: url('../fonts/23AC3F_3_0.eot?#iefix') format('embedded-opentype'),url('../fonts/23AC3F_3_0.woff') format('woff'),url('../fonts/23AC3F_3_0.ttf') format('truetype');}
```

Then I have the font files themselves in:

```
noc_pdf/fonts/
```

Should we add something similar to how images work to move those files into `assets`?

```json
"fonts" : {
  "source" : "/noc_pdf/fonts/"
}
```
